### PR TITLE
fix: image-editor toolbar height/alignment + compare aspect ratio (#1555 #1556 #1558) — VISUAL VERIFY

### PR DESCRIPTION
**Pull request by dtubb**
⚠️ **Left OPEN for Daniel — these are visual fixes (alignment / height / aspect) that need an eyeball + a real Xcode build to confirm.** Worker reported `** BUILD SUCCEEDED **` (clean xcodebuild) + swiftlint 0-serious; manager is independently re-verifying the build.

## #1555 — mini-toolbar height too short
`ImageViewerComponents.swift` (`ZoomableImagePreview`): bare HStack (~28pt) → `MiniToolbar { … }` (44pt, `.bar` material), matching the sibling `PDFPageWithToolbar`.

## #1556 — edit button misaligned
`EditorView.swift` (`editModeToggle`): fixed `.padding(10)` → `.frame(height: MiniToolbar.standardHeight, alignment: .center)` + `.padding(.trailing, 12)` to share the 44pt band + trailing inset.

## #1558 — compare forces square
`ImageEditorView.swift` (`comparePane` + wipe): added `.aspectRatio(contentMode: .fit)` to all three compare images.

### Verify checklist (Daniel)
- [ ] Build in Xcode (real index) — confirm no "unable to type-check" regression (SourceKit flagged it in the un-indexed worktree; xcodebuild passed).
- [ ] Image mini-toolbar height matches PDF/other toolbars; edit (pencil) button lines up with zoom/loupe icons.
- [ ] Side-by-side + wipe compare preserve a non-square image's aspect ratio.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by dtubb** [comment]
✅ **Build independently re-verified GREEN** by the manager (fresh worktree, real `xcodebuild clean build` → `** BUILD SUCCEEDED **`, swiftlint 0 errors). The SourceKit "unable to type-check"/"cannot find type" flags were un-indexed-worktree false positives, not real. **Only your visual eyeball remains** (toolbar height/alignment + compare aspect).
